# Generated by Django 3.0.7 on 2020-07-12 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('workplace_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.WorkPlace')),
            ],
        ),
    ]
