# Generated by Django 3.0.7 on 2020-07-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200713_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='project_manager',
        ),
    ]
