# Generated by Django 3.0.7 on 2020-07-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200715_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('ass', 'Assigned'), ('prog', 'In Progress'), ('comp', 'Completed'), ('test', 'Testing'), ('rev', 'Review'), ('appr', 'Approved'), ('rel', 'Released')], max_length=15, null=True)),
            ],
        ),
    ]
