# Generated by Django 3.0.7 on 2020-07-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200722_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Tasks'),
        ),
    ]
