# Generated by Django 3.0.7 on 2020-07-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_logs_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Tasks'),
        ),
    ]
